# code: language=ansible
---
- name: Create/update systemd unit file
  ansible.builtin.template:
    src: zoraxy.service.j2
    dest: /lib/systemd/system/zoraxy.service
    mode: "0644"
  notify: restart zoraxy
- name: Service zoraxy is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: zoraxy
    state: started
    enabled: true
# - name: allow zoraxy port
#   community.general.ufw:
#     rule: allow
#     port: "123456"
